# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef048ff7b447128248391e33e49de142dc0c34b1e37d5cca5614f9542cbddf38609f6d85dd413fb03c59a42c422eadfc962f87397e075198768f49f21372011d

test:
  secret_key_base: 6acc6bde57746dea3a2aec005a1c09064f7bd7100b299d208fe99fa193f80aef4568b36278e9c2c23574a09b3bd062478398acd27e12b6f961e12f6e293befc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
